### PR TITLE
feat: make miner retry when signature collection times out

### PR DESCRIPTION
**Pull request by obycode**
If a miner times out when waiting for signatures, it should not end its tenure. Instead it should just retry.

### CODE REVIEW

**Review by jferrant — APPROVED** [review]

**Review by jcnelson — APPROVED** [review]

**Comment by obycode** [comment]
Hmm... why didn't the CI run for this PR? @wileyj, any thoughts?

**Comment by obycode** [comment]
oh, never mind. It's a GitHub problem https://www.githubstatus.com

**Comment by obycode** [comment]
Once one of the other PRs merge, I'll merge develop into this to trigger the CI to run, now that Actions are working again.

**Comment by deantchi** [comment]
sounds good!

**Pull request merged**
