### PR TITLE
chore: Bump rusql to 0.29.0

### PR DESCRIPTION
**Pull request by jose-compu**
### Applicable issues
- fixes #

### Additional info (benefits, drawbacks, caveats)

Test passed with `cargo test testnet  -- --test-threads=1`.

### Checklist
- [X] Test coverage for new or modified code paths
- [X] Changelog is updated
- [X] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [X] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [X] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Comment by diwakergupta** [comment]
@jo-tm is this PR ready for review? I noticed you added reviewers but the PR is still marked draft 🤔

**Comment by jo-tm** [comment]
@diwakergupta it was a mistake, is a draft should not be reviewed, thanks.

**Comment by cylewitruk** [comment]
Nice! I missed that this PR existed :) Could you link this to #4046 ?

**Review by cylewitruk — COMMENTED** [review]
This LGTM in general, just needs a `cargo fmt`. And if I remember right you could actually pass simply `[]` instead of `params![]` but I could be recalling wrong... I think I personally like the explicitness of `params![]`.

**Comment by cylewitruk** [comment]
@jo-tm Would you like me to take over this PR?

**Comment by jo-tm** [comment]
@cylewitruk yes please take over the PR if you can, thanks a lot.

**Pull request closed without merging**
