### PR TITLE
Fix/4734

### LINKED ISSUE #4734: [p2p] Limit inv syncs with new peers
It's getting expensive to sync a peer inventory from scratch, and it's an increasingly fragile process (especially with stackerdb sync).  The inv state for a peer should either be kept around after disconnect (so we don't have to re-sync it), or we should avoid doing full inv syncs in the first place.

Also, a stackerdb disconnect should not result in a whole-sale peer disconnect.

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #4734 by ensuring that all inventory synchronizations happen starting from the reward cycle that is `connection_opts.inv_reward_cycles` ago, instead of 0.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
lgtm

**Review by kantai — COMMENTED** [review]
This looks good to me -- do the changes in the test code assert that this behavior changed? Can you add a comment to the test if they have?

**Comment by jcnelson** [comment]
Added a unit test

**Review by kantai — APPROVED** [review]

**Review by obycode — APPROVED** [review]
LGTM!

**Pull request merged**
