### PR TITLE
chore: Enable "fat" link-time optimizations for release builds

### PR DESCRIPTION
**Pull request by jbencin**
### Description

Enable "fat" link-time optimization. This will slow down the linking stage of release builds slightly, but will allow the linker to optimize the code better by optimizing over the entire dependency graph

A quick benchmark with `hyperfine` shows an improvement of **1%** in processing the first 3000 blocks:

```console
❯ hyperfine -w 3 -r 10 "stacks-core.next/target/release/stacks-inspect.x86-64 replay-block /home/jbencin/data/next/ first 3000" "stacks-core.next/target/release/stacks-inspect.lto-fat replay-block /home/jbencin/data/next/ first 3000"
Benchmark 1: stacks-core.next/target/release/stacks-inspect.x86-64 replay-block /home/jbencin/data/next/ first 3000
  Time (mean ± σ):     31.134 s ±  0.073 s    [User: 27.134 s, System: 3.852 s]
  Range (min … max):   31.038 s … 31.303 s    10 runs
 
Benchmark 2: stacks-core.next/target/release/stacks-inspect.lto-fat replay-block /home/jbencin/data/next/ first 3000
  Time (mean ± σ):     30.866 s ±  0.085 s    [User: 26.770 s, System: 3.953 s]
  Range (min … max):   30.749 s … 31.031 s    10 runs
 
Summary
  stacks-core.next/target/release/stacks-inspect.lto-fat replay-block /home/jbencin/data/next/ first 3000 ran
    1.01 ± 0.00 times faster than stacks-core.next/target/release/stacks-inspect.x86-64 replay-block /home/jbencin/data/next/ first 3000
```

### Applicable issues

- #4316

### Checklist

- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Review by obycode — APPROVED** [review]
Yes, this is definitely good!

**Review by wileyj — APPROVED** [review]

**Comment by jbencin** [comment]
I tried running this on a more recent block range, which should be more CPU-intensive and less dependent on filesystem operations. It shows an improvement of about **5.8%** here:

```console
❯ hyperfine -w 3 -r 10 "stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000" "stacks-core/target/release/stacks-inspect.fat-lto replay-block /home/jbencin/data/next/ range 99990 100000"
Benchmark 1: stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000
  Time (mean ± σ):     12.167 s ±  0.046 s    [User: 11.644 s, System: 0.472 s]
  Range (min … max):   12.120 s … 12.279 s    10 runs
 
Benchmark 2: stacks-core/target/release/stacks-inspect.fat-lto replay-block /home/jbencin/data/next/ range 99990 100000
  Time (mean ± σ):     11.473 s ±  0.019 s    [User: 10.950 s, System: 0.473 s]
  Range (min … max):   11.448 s … 11.504 s    10 runs
 
Summary
  stacks-core/target/release/stacks-inspect.fat-lto replay-block /home/jbencin/data/next/ range 99990 100000 ran
    1.06 ± 0.00 times faster than stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000


```

**Comment by jbencin** [comment]
Results get even better when I add `codegen-units = 1`:

```console
❯ hyperfine -w 3 -r 10 "stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000" "stacks-core/target/release/stacks-inspect.fat-lto-codegen-1 replay-block /home/jbencin/data/next/ range 99990 100000"
Benchmark 1: stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000
  Time (mean ± σ):     12.146 s ±  0.015 s    [User: 11.647 s, System: 0.450 s]
  Range (min … max):   12.124 s … 12.171 s    10 runs

Benchmark 2: stacks-core/target/release/stacks-inspect.fat-lto-codegen-1 replay-block /home/jbencin/data/next/ range 99990 100000
  Time (mean ± σ):     11.034 s ±  0.032 s    [User: 10.530 s, System: 0.453 s]
  Range (min … max):   11.007 s … 11.121 s    10 runs
 
Summary
  stacks-core/target/release/stacks-inspect.fat-lto-codegen-1 replay-block /home/jbencin/data/next/ range 99990 100000 ran
    1.10 ± 0.00 times faster than stacks-core/target/release/stacks-inspect.next replay-block /home/jbencin/data/next/ range 99990 100000
```

**Comment by jbencin** [comment]
Additionally I should mention how this affects `stacks-node` release build times. Note that these tests (and all previous tests) were run using Rust 1.76:

Using current configuration in `next`:

```console
❯ time cargo build --features monitoring_prom,slog_json --release
...
real    2m40.043s
user    24m38.295s
sys     0m38.516s
```

With `lto = "fat"` and `codegen-units = 1`:

```console
❯ time cargo build --features monitoring_prom,slog_json --release
...
real    6m44.028s
user    11m24.981s
sys     0m24.070s
```

So this more than doubles the time it takes to make a release build

**Comment by jbencin** [comment]
@wileyj @obycode I added some more test results (including build times) and made another change (added `codegen-units = 1`). I'd appreciate a quick re-review from both of you

**Comment by jbencin** [comment]
Also, I just realized this cuts the size of the `stacks-inspect` binary nearly in half:

```console
❯ ls -al target/release/
...
.rwxr-xr-x jbencin jbencin 121 MB Wed Feb 14 11:10:40 2024  stacks-inspect.fat-lto
.rwxr-xr-x jbencin jbencin 113 MB Wed Feb 14 11:16:28 2024  stacks-inspect.fat-lto-codegen-1
.rwxr-xr-x jbencin jbencin 209 MB Wed Feb 14 10:59:23 2024  stacks-inspect.next
```

**Review by jcnelson — APPROVED** [review]
LGTM

**Pull request merged**
