### PR TITLE
Chore: Merge master to develop

### PR DESCRIPTION
**Pull request by kantai**
This merges the latest from master to develop. The conflicts were in `CHANGELOG.md`, and in commented out code in `v1::signer`

### CODE REVIEW

**Comment by wileyj** [comment]
hmm, master could use a merge from `release/2.5.0.0.5`, else we'll be doing this again after that (only 2 PR's missing - one for the default antientropy_rety and another for the changelog). 

better to wait on this PR until that one is merged?

**Comment by kantai** [comment]
> hmm, master could use a merge from release/2.5.0.0.5, else we'll be doing this again after that (only 2 PR's missing - one for the default antientropy_rety and another for the changelog).
>
> better to wait on this PR until that one is merged?

Yep, happy to wait on that. Will close.

**Comment by wileyj** [comment]
https://github.com/stacks-network/stacks-core/pull/4947

**Review by obycode — APPROVED** [review]
LGTM

**Review by wileyj — APPROVED** [review]

**Pull request merged**
