### PR TITLE
fix: fix delegate stack increase events

### PR DESCRIPTION
**Pull request by janniks**
- missing `)` in injected code was causing an event to not emit

> not consensus critical, but very important for the api

### CODE REVIEW

**Review by kantai — APPROVED** [review]
LGTM, assuming the CI passes.

**Review by wileyj — APPROVED** [review]
copypaste of @kantai comment

**Review by zone117x — APPROVED** [review]
Good find!

**Comment by janniks** [comment]
Thanks to @rafaelcr 🕵

**Pull request merged**
