### PR TITLE
Fix/5502

### LINKED ISSUE #5502: FATAL: called a nakamoto function outside of epoch 3
**Describe the bug**
On running Stacks node using docker with image release:3.0.0.0.3 node crashes with panic: `FATAL: called a nakamoto function outside of epoch 3`

**Steps To Reproduce**
It is not clear if it is reproducible or not. However, the suggestion to resync the node to try reproducing it could be challenging at the moment due to the node's slow syncing speed

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 12 as a host machine
 - Docker release: release-3.0.0.0.3

**Additional context**
Logs:
```
INFO [1732537880.760897] [stackslib/src/chainstate/nakamoto/coordinator/mod.rs:1085] [chains-coordinator-0.0.0.0:20443] Process burn block 817251 reward cycle 72 in /var/stacks-blockchain-data/mainnet/burnchain, in_prepare_phase: false, is_rc_start: true, is_prior_in_prepare_phase: true, burn_block_hash: 000000000000000000036061c227a69ea9ef8cd4459b4992982c989eb5f5591a
ERRO [1732537880.761261] [testnet/stacks-node/src/main.rs:257] [chains-coordinator-0.0.0.0:20443] Process abort due to thread panic: panicked at /build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:314:5:
FATAL: called a nakamoto function outside of epoch 3
ERRO [1732537880.829133] [testnet/stacks-node/src/main.rs:259] [chains-coordinator-0.0.0.0:20443] Panic backtrace:    0: stacks_node::main::{{closure}}
             at build/testnet/stacks-node/src/main.rs:258:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2245:9
      std::panicking::rust_panic_with_hook
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:805:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:664:13
   3: std::sys::backtrace::__rust_end_short_backtrace
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:170:18
   4: rust_begin_unwind
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   5: core::panicking::panic_fmt
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   6: blockstack_lib::chainstate::nakamoto::coordinator::get_nakamoto_reward_cycle_info
      blockstack_lib::chainstate::nakamoto::coordinator::<impl blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE,B>>::get_nakamoto_reward_cycle_info
             at build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:989:9
      blockstack_lib::chainstate::nakamoto::coordinator::<impl blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE,B>>::handle_new_nakamoto_burnchain_block
             at build/stackslib/src/chainstate/nakamoto/coordinator/mod.rs:1140:21
   7: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE,B>::handle_new_burnchain_block
             at build/stackslib/src/chainstate/coordinator/mod.rs:2421:9
      blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSetProvider<T>,CE,FE,B>::handle_comms_epoch2
             at build/stackslib/src/chainstate/coordinator/mod.rs:599:19
   8: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSetProvider<T>,CE,FE,B>::run
             at build/stackslib/src/chainstate/coordinator/mod.rs:565:21
   9: stacks_node::run_loop::neon::RunLoop::spawn_chains_coordinator::{{closure}}
             at build/testnet/stacks-node/src/run_loop/neon.rs:633:17
      std::sys::backtrace::__rust_begin_short_backtrace
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/backtrace.rs:154:18
  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/mod.rs:522:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panic/unwind_safe.rs:272:9
      std::panicking::try::do_call
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:554:40
      std::panicking::try
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:518:19
      std::panic::catch_unwind
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panic.rs:345:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/thread/mod.rs:521:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2231:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/boxed.rs:2231:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/sys/pal/unix/thread.rs:105:17
  12: <unknown>
  13: __clone

Dumping core for pid 7
```

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #5502.  I have confirmed it with a genesis sync.  It works by preventing the chains coordinator from advancing the sortition view until the corresponding PoX anchor block is found.  This is now an unconditional requirement, since we know for a fact that all reward cycles have a PoX anchor block (and as of Nakamoto, _msut- have one).  It paves the way for removing the entirety of the affirmation map subsystem.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
Nice

**Comment by jferrant** [comment]
Wow so much red! Noice!

**Review by jferrant — DISMISSED** [review]

**Review by obycode — DISMISSED** [review]
👍

**Comment by jcnelson** [comment]
ping @obycode @jferrant for quick re-review -- I added a changelog entry.

**Review by obycode — APPROVED** [review]

**Review by jferrant — DISMISSED** [review]

**Comment by jcnelson** [comment]
ping @obycode @jferrant one more time -- had to clear a merge conflict.  Thanks!

**Review by obycode — APPROVED** [review]

**Comment by jcnelson** [comment]
Ping @jferrant @hstove @jbencin plz :pray:

**Review by jferrant — APPROVED** [review]

**Pull request merged**
