### PR TITLE
fix: update prepare offset of start-end cycle ids

### PR DESCRIPTION
**Pull request by janniks**
- update `prepare_offset` to more fitting `pox_set_offset`
- this fixes an off-by-one error in the check for which pox txs could still be considered in the next cycle.

* adds more tests along the prepare phase border
* non consensus critical, but will output different event values

### Checklist

- [x] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

---

~_I wanted to add checks to the end of the tests to check whether the addresses are actually in (or not in) the pox-set (reward_addresses), but I couldn't get the Rust to work 🙈 If somebody has ideas on how to best do that from a TestPeer._~ thx Brice

### CODE REVIEW

**Review by zone117x — DISMISSED** [review]
Thanks @janniks!

**Review by kantai — COMMENTED** [review]
This LGTM, but can you rebase and redirect this PR against `develop` instead of `next` (I suppose we want this in the 2.5 release candidates).

**Comment by janniks** [comment]
Yes, will do 👍🏻

**Comment by janniks** [comment]
Rebased -- feel free to triple check the pox-set-offset logic 😅🙏

**Review by kantai — APPROVED** [review]
LGTM!

**Review by zone117x — DISMISSED** [review]

**Review by jcnelson — APPROVED** [review]

**Review by kantai — APPROVED** [review]

**Review by zone117x — APPROVED** [review]

**Pull request merged**
