### PR TITLE
Feat/wasm global variable error

### PR DESCRIPTION
**Pull request by csgui**
This PR adds a generic wasm error for globals on clarity-wasm standard library.

New global variables will be added to the `Standard.wat` WebAssembly file. For instance, a new variable to handle runtime errors is under validation on this [PR](https://github.com/stacks-network/clarity-wasm/pull/379/files#diff-0dbeb8ed9c7228c4c202b84da52fadf9f0aa8985b4c27617f5763c744c9f87b2R3426).

Thus, it makes sense to have a generic WASM error to avoid creating a new error type for each global added to the WebAssembly.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
lgtm. thanks Chris!

**Comment by obycode** [comment]
Please check these failing unit tests. Were they caused by this change?

**Comment by csgui** [comment]
Hey @obycode ! Thanks for the review.

It appears the failing unit tests were imported from the base branch `feat/clarity-wasm-develop`. And consequently, the failing mutants are due to these failed unit tests.

**Comment by csgui** [comment]
Merging. The failing tests will be fixed in the base branch.

**Pull request merged**
