### PR TITLE
chore: add debug logs before all `stacks_node_client` use

### PR DESCRIPTION
**Pull request by obycode**
More logs to help with triaging issues.

### CODE REVIEW

**Comment by obycode** [comment]
@hstove I was noticing the timers present on some of these calls. Do we want to add it to the others as well, or there a specific subset that you were targeting?

**Comment by jferrant** [comment]
Am seeing some build issues.

**Review by jferrant — APPROVED** [review]

**Review by hstove — DISMISSED** [review]

**Review by jcnelson — APPROVED** [review]

**Review by jcnelson — APPROVED** [review]

**Comment by wileyj** [comment]
@obycode some merge conflicts, saving approval for when those are fixed

**Comment by obycode** [comment]
Resolved.

**Review by saralab — APPROVED** [review]

**Pull request merged**
