### PR TITLE
Drop User Burn Support

### LINKED ISSUE #4071: [Nakamoto] Drop user burn support
This is an opcode we never implemented because there was never any economic incentive to use it.  Let's delete it.

### PR DESCRIPTION
**Pull request by 8marz8**
### Description
Removing UserBurnSupportOp definition and usage throughout the codebase as it's not fully implemented and used.

### Applicable issues

- closes #4071

### CODE REVIEW

**Comment by 8marz8** [comment]
@jcnelson @kantai Should "StagingUserBurnSupport" also be deleted?

**Review by jcnelson — DISMISSED** [review]
LGTM. Thanks for taking care of this!

**Comment by jcnelson** [comment]
Also, yes -- feel free to remove `StagingUserBurnSupport`.  As long as CI passes, it should be fine.

**Review by kantai — COMMENTED** [review]
These changes look fine to me, but I do have a question, that's probably more for @jcnelson than @8marz8:

`UserBurnSupport` transactions are currently not considered for reward distribution or miner commitment distributions, however, they are _parsed_ currently, correct? This would mean that they are included in the `OpsHash` and therefore `ConsensusHash`, meaning that any change to remove it from the `OpsHash` would need to be epoch-gated, right?

**Review by kantai — DISMISSED** [review]
LGTM! I tested in a separate branch (because you can't test whether or not a UserBurn is parsed in this branch), and UserBurn ops are never parsed under 2.x consensus rules.

**Review by kantai — APPROVED** [review]

**Review by jcnelson — APPROVED** [review]

**Pull request merged**
