### PR TITLE
feat: gate `target-cpu=native` with `portable` feature

### PR DESCRIPTION
**Pull request by obycode**
We believe this flag can cause some problems with docker images.

### CODE REVIEW

**Review by CharlieC3 — APPROVED** [review]
Related PR: https://github.com/stacks-network/stacks-core/pull/4460

The PR linked above explicitly defines the CPU target when an image is being built via GHA. But when this Docker image is being built locally (which I've had to do numerous times) intended for cloud deployments, it'll be helpful for have this feature flag in place to ensure the image is being built the same way it's always been, which has been compatible with most cloud infra.

I would suggest getting @wileyj's approval in this before merging as well.

**Comment by obycode** [comment]
So maybe it would be good to have that "portable" feature enabled conditionally, with an environment variable for example?

**Comment by CharlieC3** [comment]
> So maybe it would be good to have that "portable" feature enabled conditionally, with an environment variable for example?

@obycode I actually like the way you have it right now. In the scenario I painted above when I need to build the image locally, I use the `.github/actions/dockerfiles/Dockerfile.debian-source` Dockerfile. So this PR effectively helps my specific workflow while leaving the others untouched.
So if a dev wants to build from source, unless they're using the `.github/actions/dockerfiles/Dockerfile.debian-source`, it would still build using the `native` CPU target. If there's an ENV var required, I feel it's another manual step I may forget.

**Comment by obycode** [comment]
> @obycode I actually like the way you have it right now. In the scenario I painted above when I need to build the image locally, I use the `.github/actions/dockerfiles/Dockerfile.debian-source` Dockerfile. So this PR effectively helps my specific workflow while leaving the others untouched. So if a dev wants to build from source, unless they're using the `.github/actions/dockerfiles/Dockerfile.debian-source`, it would still build using the `native` CPU target. If there's an ENV var required, I feel it's another manual step I may forget.

Ah, got it. Thanks for clarifying!

**Review by zone117x — APPROVED** [review]

**Pull request merged**
