### PR TITLE
Chore: Set 3.0 mainnet activation height

### PR DESCRIPTION
**Pull request by kantai**
This sets the 3.0 (Nakamoto) epoch activation height to BTC block 867,867

### CODE REVIEW

**Comment by saralab** [comment]
LFG!!!! 
#867867 #42 
🎉

**Review by wileyj — APPROVED** [review]

**Review by obycode — APPROVED** [review]
🚀

**Review by jcnelson — APPROVED** [review]
:partying_face:

**Comment by muneeb-ali** [comment]
It's Nakamoto time! 867,867 🟧 🚀

**Pull request merged**
