### PR TITLE
fix: Rust 1.80 warnings

### PR DESCRIPTION
**Pull request by jbencin**
### Description

Building with Rust 1.80 outputs dozens of warnings. It looks like the new version of Rust does not like using undeclared `#[cfg(...)]` attributes. This PR fixes these new warnings by declaring or removing them.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
Lgtm!

**Review by kantai — COMMENTED** [review]
I think my preference for addressing this would be to delete the unused code (or in the case of the testnet/stacks-node `testing` feature, just simplify the flags to `cfg(test)`)

**Comment by jbencin** [comment]
@kantai which do you think are unnecessary? I was hesitant to remove anything because I don't know if it's used by other projects like Clarinet. Here are the ones I think can go:
- `feature = "clippy"` is not necessary, I'll remove
- `feature = "testing"` is used in some crates because `cfg(test)` isn't passed to dependencies. Yeah, shouldn't be necessary in a binary crate like `stacks-node`
- In `bech32` we've been using their `no_std` version this whole time. Seems like a minor risk to change, so just remove `std`?

The others seem like they are or may be used somewhere

**Comment by kantai** [comment]
> feature = "clippy" is not necessary, I'll remove
> feature = "testing" is used in some crates because cfg(test) isn't passed to dependencies. Yeah, shouldn't be necessary in a binary crate like stacks-node

Yep -- I think in this case, it can just be removed as a flag in crates like `stacks-node`

> In bech32 we've been using their no_std version this whole time. Seems like a minor risk to change, so just remove std?

Yep, I think just remove std.

> The others seem like they are or may be used somewhere

I don't think any of them can be used at the moment. Otherwise, the warnings wouldn't show up, right? My worry about adding the feature flags is that, ultimately, these functions aren't included in CI, testing, etc., and so I worry that someone might believe that the features actually work and are tested and build with them enabled.

**Review by jcnelson — APPROVED** [review]

**Comment by jbencin** [comment]
> `feature = "testing"` is used in some crates because cfg(test) isn't passed to dependencies. Yeah, shouldn't be necessary in a binary crate like stacks-node

On second thought, I think this should stay. If we set the feature flag `testing` on stacks-node, it should be passed down to the dependencies (stackslib, stacks-common, etc.), which do use it

> I don't think any of them can be used at the moment

Cargo currently doesn't let you build with feature flags not declared in Cargo.toml, but I don't know if that's always been the case. For example, `docs/profiling.md` instructs the user to run `cargo build -F disable-costs`. Did we remove the feature flag without removing the associated code, or was it once possible to use undeclared feature flags?

**Review by obycode — APPROVED** [review]

**Review by kantai — APPROVED** [review]

**Pull request merged**
