### PR TITLE
Chore/next to develop

### PR DESCRIPTION
**Pull request by obycode**
Merge next into develop to get the latest signer fixes. There should be no consensus breaking changes in this changeset.

### CODE REVIEW

**Comment by wileyj** [comment]
@obycode is this required for rc2?

**Review by jferrant — APPROVED** [review]

**Comment by jferrant** [comment]
> @obycode is this required for rc2?

Should not be. This is to port signer changes out of next since signer changes are not consensus breaking and subsequent signer dev should be done from develop. See https://nakamotoslack.slack.com/archives/C067BHSN1SL/p1712679342282899

**Comment by wileyj** [comment]
> > @obycode is this required for rc2?
> 
> Should not be. This is to port signer changes out of next since signer changes are not consensus breaking and subsequent signer dev should be done from develop. See https://nakamotoslack.slack.com/archives/C067BHSN1SL/p1712679342282899

ok - let's hold off on merging this then until rc2 is tagged

**Comment by hstove** [comment]
> is this required for RC2?

> should not be

I understand the reasoning, but unless we have a different release system for the signer, we still really want these changes included when people update or set up their infra. Otherwise, we're just punting these important changes for some later release.

**Comment by obycode** [comment]
> ok - let's hold off on merging this then until rc2 is tagged

Since we're releasing from the `release/...` branch now, I think we're clear to merge this. Please confirm.

**Comment by obycode** [comment]
I just updated this PR with the latest `next` and `develop`. Let's get it merged today.

**Comment by obycode** [comment]
Note, there were no conflicts, so this should be a simple review.

**Pull request merged**
