### PR TITLE
BNS Documentation Review

### PR DESCRIPTION
**Pull request by kantai**
Opening a PR, as it's a little easier to track comments and discussion than on a file or issue.

I like that this document provides a high-level overview of what BNS is, how it is used, and why. I'm left with a couple questions after reading the document though:

* Who owns a name, is it a public-key? is that an RSA key? 
* How much name data can I store? What about off-chain (I understand that's a topic for the Atlas doc, but I think we should clarify that it's more than just the 'common use-case' to store a hash and link that hash to data in Atlas -- we should just say that _only_ the hash is part of the consensus code, however, BNS _does_ rely on Atlas).

I think those two questions should be answerable by someone after _just_ reading the intro.

These questions are more detailed, and surround what I can do with a name, and probably belong
in their own section:

* What are the operations I can make on my name, and why do I want to make them?
* What are the semantics of those operations?
(i.e., what does a RENEW do? what is the relationship between the PREORDER address and the REGISTER operation? Can any address broadcast a REGISTER, or does it have to be the payer of the PREORDER?)

### CODE REVIEW

**Comment by kantai** [comment]
Tagging @jcnelson for the discussion

**Comment by jcnelson** [comment]
Thanks for your review @kantai!

> How much name data can I store? What about off-chain (I understand that's a topic for the Atlas doc, but I think we should clarify that it's more than just the 'common use-case' to store a hash and link that hash to data in Atlas -- we should just say that only the hash is part of the consensus code, however, BNS does rely on Atlas).

I struggled with this as well when writing the document.  I think the fundamental question is, how inseparable are BNS and Atlas?  I had taken the stance in the document that Atlas was a completely separate component, and that BNS only concerned itself with resolving names to their public key hash and their 20-byte payload.  Alternative use-cases for the 20-byte payload include things like:

* short human-readable messages
* IP addresses
* short URLs
* app-level control-plane messages

These are not common use-cases, however.  Do you feel like it's better for incoming developers to assume that Atlas is simply part of BNS, and that the 20-byte payload is *always* a zone file hash?

> What are the semantics of those operations?

I agree that we could expand this section.  Will take a crack.

**Comment by kantai** [comment]
Okay -- I added some more detailed comments to the markdown file -- but I think it's misleading to present Atlas as separable, especially when the same document covers subdomains.

**Comment by kantai** [comment]
> These are not common use-cases, however. Do you feel like it's better for incoming developers to assume that Atlas is simply part of BNS, and that the 20-byte payload is always a zone file hash?

Yeah, I think that's better.

**Comment by jcnelson** [comment]
Thanks for your review!  I implemented your recommendations.  Can you take another look when you get a chance? https://github.com/blockstack/blockstack-core/blob/master/docs/blockstack_naming_service.md

**Comment by kantai** [comment]
These changes look great, thanks @jcnelson !

**Pull request closed without merging**
