### PR TITLE
chore: sync host functions with clarity-wasm implementation

### PR DESCRIPTION
**Pull request by csgui**
Sync host functions.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
This looks good to me. The "Unchanged files with check annotations" makes me think that we missed something in the last merges, because wits should have been removed.

**Comment by csgui** [comment]
@hugocaillard can you please check the changes for `secp256k1` module?

**Comment by hugocaillard** [comment]
Apparently the compilation to wasm was broken earlier on feat/clarity-wasm-develop. I'll just need to add this feature flag `#[cfg(feature = "canonical")]` [here](https://github.com/stacks-network/stacks-core/blob/2d287f07ffc32421f7828a14b6e03c66bca9c822/stacks-common/src/util/mod.rs#L22)
Will do in a follow up PR

**Review by hugoclrd — APPROVED** [review]
LGTM!

**Pull request merged**
