### PR TITLE
Update wsts to the correct 4.0.0 version and fix compile issues

### PR DESCRIPTION
**Pull request by jferrant**
### Description
This breaks work out of the nakamoto signature validation ticket to fix the wsts version. 

### Applicable issues
- fixes https://github.com/stacks-network/stacks-blockchain/issues/4040

### Additional info (benefits, drawbacks, caveats)
I also was able to remove the p256k1 dependency by utilizing just the wsts code.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
👍

**Review by xoloki — APPROVED** [review]
LGTM.  Didn't we already do this on `develop` branch though?

**Comment by jferrant** [comment]
> LGTM. Didn't we already do this on `develop` branch though?

A good question... We may have....Let me check

**Comment by jcnelson** [comment]
We'll need to open a PR from `develop` to `next` and resolve all the merge conflicts.

**Review by kantai — APPROVED** [review]

**Review by jcnelson — APPROVED** [review]

**Comment by saralab** [comment]
Closing this, merge from develop to next fixes this

**Pull request closed without merging**
