### PR TITLE
chore: improve signer logging

### PR DESCRIPTION
**Pull request by obycode**

### CODE REVIEW

**Comment by jferrant** [comment]
Confused as to why empty sortition is failing. This test passes locally for me in develop and in this PR.

**Review by jferrant — APPROVED** [review]

**Comment by obycode** [comment]
> Confused as to why empty sortition is failing. This test passes locally for me in develop and in this PR.

Yeah that is strange. Clearly not related to these changes.

**Comment by wileyj** [comment]
> > Confused as to why empty sortition is failing. This test passes locally for me in develop and in this PR.
> 
> Yeah that is strange. Clearly not related to these changes.

I've noticed the same - confirmed it passes locally, so i wouldn't worry about it for now since other things are higher priority. 
i'll create an issue to track it

**Review by ASuciuX — APPROVED** [review]
LGTM, i wouldn't worry about the unviable mutant https://github.com/stacks-network/stacks-core/actions/runs/10185995218?pr=5025.

**Pull request merged**
