### PR TITLE
Remove deadlock introduced in commit 1d836175730eff88eaec9440c608267eb6303494

### PR DESCRIPTION
**Pull request by jferrant**
Jude found the deadlock introduced in a prior commit.

### CODE REVIEW

**Review by jcnelson — DISMISSED** [review]

**Review by obycode — COMMENTED** [review]
Good catch! Looks like there are still some changes needed in some tests.

**Comment by jferrant** [comment]
> Good catch! Looks like there are still some changes needed in some tests.

Yep :D Done!

**Review by obycode — APPROVED** [review]
LGTM!

**Comment by obycode** [comment]
Post-Nakamoto, I think some refactoring is in order to help prevent these DB-related deadlocks.

**Review by jcnelson — APPROVED** [review]

**Pull request merged**
