### PR TITLE
fix: 2 blocks dead time between 2.5 -> 3.0 transition

### LINKED ISSUE #4710: Nakamoto Miner[3.0] - Fix the 2 blocks dead time between 2.5 -> 3.0 transition
In the current 2.5 -> 3.0 transition, when the 3.0 block height is reached the `Ne` miner tears down and the Naka miner starts up. This leads to a 2 block dead time. 

- `Ne` miner tears down a block early at the 3.0 transition height
-  Naka miner spins up 
-  Naka miner submits VRF key registration that needs to be accepted to next block 

Fix: 
- Solution for this involves Ne submitting a VRF key registration formatted for 3.0 during 2.5 [2.5.X release] 
- Miners should update to this ahead of the 3.0 release

### PR DESCRIPTION
**Pull request by jbencin**
### Description

Fix 2 block downtime by passing `LeaderKeyRegistrationState` from Neon runloop to Nakamoto runloop

### Applicable issues

- fixes #4710

### Checklist

- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Comment by jbencin** [comment]
Passing `leader_key_registration_state` into the Nakamoto run loop may not be the best approach. It only works in one of 3 possible scenarios:

- ✔️ Neon and Nakamoto miner using same private key
- ❌ Neon and Nakamoto miner using different private key
- ❌ Neon miner using no private key

Maybe almost all miners are doing the first, so the other two don't really matter? Or maybe I just need to explicitly register the VRF pubkey with the Nakamoto miner pubkey hash before Epoch 3.0

**Comment by obycode** [comment]
The tests in testnet/stacks-node/src/tests/nakamoto_integrations.rs are going to need to be updated, as most (all?) of them expect to wait for this key registration. It would be great to also add a case to test for your scenarios 1, 2, and 3 in there.

**Comment by jbencin** [comment]
I've fixed all the integration tests except for `signer::v1`, but those are failing on `develop` as well right now, so I don't think I broke them here

**Review by kantai — APPROVED** [review]
LGTM!

**Review by obycode — APPROVED** [review]
LGTM!

**Pull request merged**
