### PR TITLE
[sBTC] 3553 add burn ops rpc for pegout

### PR DESCRIPTION
**Pull request by stjepangolemac**
### Description
Uses a temporary branch as a base until some prerequisite work is merged into next.

### Applicable issues
- adds the PegOut RPC

### Checklist
- [ ] Test coverage for new or modified code paths (@netrome seems some related tests were added in the peg out wire format PR, do we need additional tests?)

### CODE REVIEW

**Comment by stjepangolemac** [comment]
@kantai do we have any tests for API responses? This diff seems suspiciously small and that's the only thing that crossed my mind, so I might've missed it. Also, let me know if you find that something is missing.

**Comment by netrome** [comment]
We also should extend the `test_submit_and_observe_sbtc_ops` test in `neon_integrations.rs`. This won't test the serialized format of API responses though, but at least verifies that the API picks up new peg out requests and peg out fulfillments.

**Review by netrome — CHANGES_REQUESTED** [review]
Generally looks good to me.  One request, can we add a serialization test similar to what Aaron added here https://github.com/stacks-network/stacks-blockchain/pull/3511/files#diff-0cc1d8499a6219cd0467abfddd7ae0eb6e5269b10df975cf68d79b35d70867e4?

**Comment by stjepangolemac** [comment]
I'll need to create another prereq branch from the latest parent branches:

- `feat/sbtc-burn-ops-rpc`
- `3493-sbtc-peg-out-wire-format`

**Comment by jcnelson** [comment]
If it's for sBTC, please label it as such.  Thanks!

**Comment by netrome** [comment]
> If it's for sBTC, please label it as such. Thanks!

Done. This is to be incorporated in #3577 since the changes introduced here are minimal and closely related to it. I'm closing this PR since we don't intend to merge this one.

**Pull request closed without merging**
