### PR TITLE
Chore: Remove `Box`ing of `SymbolicExpression`s

### LINKED ISSUE #4445: [Chore] Remove `Box`ing of `SymbolicExpression`s in Clarity
`SymbolicExpression`s are unnecessarily `Box`'d in a few places in the `clarity` crate when used in `Vec`s. As `Vec`s are already on the heap, a `Box` is not necessary.

### PR DESCRIPTION
**Pull request by ASuciuX**
### Description
`SymbolicExpression`s and `PreSymbolicExpression`s are unnecessarily `Box`ed in a few places in the `clarity` crate when used in `Vec`s. As `Vec`s are already on the heap, a `Box` is not necessary.

Closes #4445

### CODE REVIEW

**Review by cylewitruk — APPROVED** [review]
Lgtm :) This suggestion stemmed from playing with different binary serialization formats, which aren't as forgiving as JSON.

**Comment by jcnelson** [comment]
@kantai Is there a reason we were `Box`-ing these before?

**Comment by kantai** [comment]
Classic case of early optimization, I think. These structs never need to be resized, so boxed slices were maybe a closer match to their usage than vecs. No real reason that they need to be boxed slices instead of vecs, though, and I doubt that there's a performance benefit to keeping them as boxed slices (I wouldn't be surprised if it was the opposite).

**Review by jcnelson — APPROVED** [review]
If it's fine with @kantai it's fine with me :+1:

**Review by kantai — APPROVED** [review]

**Comment by jbencin** [comment]
> I doubt that there's a performance benefit to keeping them as boxed slices (I wouldn't be surprised if it was the opposite).

They compile to pretty much the same thing. A `Box`ed slice is represented on the stack with 2 elements: `ptr` and `len`. `Vec` has an additional element: `capacity`. So the cost of using a `Vec` is just an extra `usize`, which is trivial

**Comment by cylewitruk** [comment]
Boxed slices also had issues with several binary encodings I tried for these types, where Vecs were handled otob -- that's essentially the birth place of the issue, preparing for that kind of change.

**Pull request merged**
