### PR TITLE
Fix: Conditional logging for 'Proceeding to mine blocks' message

### LINKED ISSUE #4944: Node always logs "Proceeding to mine blocks" regardless of miner status
On a follower node, I see the following as expected:

```
INFO [1719960965.695137] [testnet/stacks-node/src/run_loop/neon.rs:384] [main] Will run as a Follower node
```

However, shortly after I also see:
```
INFO [1719960987.613683] [testnet/stacks-node/src/run_loop/neon.rs:1341] [main] Runloop: Synchronized full burnchain up to height 850443. Proceeding to mine blocks
```

This is confusing and incorrect, since this node is not a miner.

The code in question doesn't have any conditionals around miner status for this log message:
https://github.com/stacks-network/stacks-core/blob/master/testnet/stacks-node/src/run_loop/nakamoto.rs#L705

### PR DESCRIPTION
**Pull request by Parikalp-Bhardwaj**
### Summary
This PR fixes an issue where the node logs `Proceeding to mine blocks` even when running as a follower node. The log message is now conditional on the node being a miner.

### Changes
- Added a conditional check around the log message to ensure it only appears when the node is configured as a miner.

### Related Issues
- Closes #4944

### CODE REVIEW

**Review by obycode — APPROVED** [review]
Good idea. Thanks for the PR @Parikalp-Bhardwaj!

**Comment by hstove** [comment]
Should we target this to `develop` instead of `master`?

**Comment by obycode** [comment]
> Should we target this to `develop` instead of `master`?

Yes, good point.

**Comment by obycode** [comment]
Replaced with #5348

**Pull request closed without merging**
