### PR TITLE
fix: Rename `.cargo/config` -> `.cargo/config.toml` to fix warning

### PR DESCRIPTION
**Pull request by jbencin**
### Description

The latest release of Rust (1.78) gives a warning if you have a file named `.cargo/config`. I renamed it to `.cargo/config.toml`, as suggested by Cargo, to silence the warning.

### CODE REVIEW

**Review by ASuciuX — DISMISSED** [review]

**Comment by obycode** [comment]
Looks like we need a corresponding change in https://github.com/stacks-network/actions/blob/c822d00b31e61951d72a4c051e30887afd930036/rustfmt/action.yml#L37C57-L37C63

Please also update the mentions of this file in docs/profiling.md and README.md.

**Comment by jbencin** [comment]
Opened PR in actions repo here: stacks-network/actions#42

**Comment by jbencin** [comment]
> Please also update the mentions of this file in docs/profiling.md and README.md

Done

**Review by obycode — APPROVED** [review]
This looks good to me. We'll need @jw to help with the timing of the update to the action.

**Comment by wileyj** [comment]
> This looks good to me. We'll need @jw to help with the timing of the update to the action.

the action PR has been merged. i'll tigger a re-run here to see if checks pass now

**Review by wileyj — APPROVED** [review]
shipit

**Pull request merged**
