### PR TITLE
Add skips and comments for certain mutants 

### PR DESCRIPTION
**Pull request by ASuciuX**
Related issue #4587 

List of PRs addressed:
- [x] #4412
- [x] #4414 
- [x] #4527
- [x] #4530
- [x] #4556 
- [x] #4560 
- [x] #4561 
- [x] #4575 
- [x] #4576 
- [x] #4578

### CODE REVIEW

**Comment by ASuciuX** [comment]
This follows the same structure as https://github.com/stacks-network/stacks-core/pull/4593 which was previously merged. It includes the mutants for multiple PRs.

**Review by jbencin — COMMENTED** [review]
I think the associated comments should be regular comments, not doc comments. `cargo doc` is great for figuring out how to use an API, and these comments don't help anyone actually *use* the functions

**Comment by ASuciuX** [comment]
> I think the associated comments should be regular comments, not doc comments. `cargo doc` is great for figuring out how to use an API, and these comments don't help anyone actually _use_ the functions

Those comments act as placeholders for missing tests, they should be reference for who wants to write the test cases that are in the comments and aren't treated by the functions. There should be something on the code to point to the specific missing cases so that a developer could know which test cases to add. Would it be enough to change them to simple comments instead of doc comments? Or do you think we should move them somewhere externally but also keep a short reference so that the cases can be seen when going to that external source. Also curious what that external source should be and how should I give access to the others to modify it if some of the tests are added.

**Comment by jbencin** [comment]
> Would it be enough to change them to simple comments instead of doc comments?

This is fine by me. Although you should add a second reviewer on here for another opinion

**Comment by ASuciuX** [comment]
> > Would it be enough to change them to simple comments instead of doc comments?
> 
> This is fine by me. Although you should add a second reviewer on here for another opinion

I've added the blockchain team, but it treated your review in that behalf, so I'll add it again.

**Comment by ASuciuX** [comment]
@jbencin I've updated this to have regular comments

**Comment by ASuciuX** [comment]
As this is outdated and for `next` branch, I will move it to `develop`.

**Comment by ASuciuX** [comment]
Migrated the PR here https://github.com/stacks-network/stacks-core/pull/4790.

**Pull request closed without merging**
