### PR TITLE
Fix/4732

### LINKED ISSUE #4732: [StackerDB] only attempt at most one connection to a remote replica at once
Right now, the node will attempt to cold-call a replica once for each stackerdb it advertises. It should instead do so only once.  Today, it tries to open one connection to each replica, and will immediately close all but the first once it realizes that it has already connected.

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #4732 by tracking pending connections in addition to completed connections, so that the state machine for StackerDB doesn't re-attempt a handshake if it already has one in-flight.  It also disables disconnection from dead/broken StackerDB peers, since a StackerDB peer's inability to reply to a StackerDB request (itself a best-effort replication system) should not be grounds for disconnecting from and banning the node in its entirety.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
Makes sense to me. Does this seem to make a difference in practice?

**Review by obycode — APPROVED** [review]

**Comment by jcnelson** [comment]
Okay, I have this running on my node, and have tested it in both IBD and steady-state modes of operation.  No duplicate connections have been established.

**Review by obycode — DISMISSED** [review]

**Comment by jcnelson** [comment]
ping @kantai

**Comment by jcnelson** [comment]
(note that this is blocking the next point release)

**Review by kantai — COMMENTED** [review]
These changes look fine to me, but reading through this PR, it's not really clear to me exactly what behavior is being changed, and why, and how it is tested. It seems like there isn't sufficient testing here to prevent a regression: the only testing change is an assertion about the number of connections, which I can imagine being related to some of these changes, but not all of them.

**Comment by jcnelson** [comment]
@kantai I added some regression tests for the new functionality

**Comment by obycode** [comment]
There are [some build issues](https://github.com/stacks-network/stacks-core/actions/runs/9069571223/job/24919436784?pr=4759) with the latest version.

**Review by kantai — APPROVED** [review]

**Review by obycode — APPROVED** [review]

**Pull request merged**
