### PR TITLE
feat: add `block_commit_delay_ms` config option

### PR DESCRIPTION
**Pull request by obycode**
This option defines the number of ms to wait after seeing a new burn block before submitting a block commit, allowing time for the first Nakamoto block to arrive so that the block commit does not need to be RBFed.

Fixes: #5064

### Checklist

- [x] Test coverage for new or modified code paths
- [x] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [x] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Comment by jferrant** [comment]
I think this breaks a lot of tests because of the default value. You might need to update those tests to have either a much shorter or much longer timeout depending on what they are trying to achieve.

**Comment by obycode** [comment]
Ok, I just set the value to 0 in those three tests. I think it makes sense in those cases, but please verify.

**Comment by obycode** [comment]
Doing some further digging into the newly failing tests...

**Comment by obycode** [comment]
@jcnelson I may need some help debugging this failing integration test. https://github.com/stacks-network/stacks-core/actions/runs/11692987634/job/32564093185. I can't figure out why the follower stalls. It reports, "No PoX anchor block known yet for cycle 12", then "Missing canonical anchor block", followed by "remote peer NACKed our GetNakamotoInv, remote_peer: ... error_code: 2". I'm unclear why my change would have any effect on that.

I tried increasing the `pox_sync_sample_secs` to 180 with no effect.

**Comment by jferrant** [comment]
> @jcnelson I may need some help debugging this failing integration test. https://github.com/stacks-network/stacks-core/actions/runs/11692987634/job/32564093185. I can't figure out why the follower stalls. It reports, "No PoX anchor block known yet for cycle 12", then "Missing canonical anchor block", followed by "remote peer NACKed our GetNakamotoInv, remote_peer: ... error_code: 2". I'm unclear why my change would have any effect on that.
> 
> I tried increasing the `pox_sync_sample_secs` to 180 with no effect.

Confirmed this is unrelated to Brice's PR as its flaky on mine too: https://github.com/stacks-network/stacks-core/actions/runs/11694282070/job/32568007933?pr=5425

But I have no idea how to fix this issue. Miner_forking has been flaky for a while too with similar reports about "Missing PoX anchor block" and "No PoX anchor block" warnings. I thought increasing the pox_sample_sync_secs would fix it but it doesn't :(

**Comment by jcnelson** [comment]
I'll take a look once I've fixed my downloader PR tests.

**Comment by obycode** [comment]
The miner is hitting the "No such block snapshot for ..." error case for burn block 221. However, I see that the consensus hash matches the one reported by the `CONSENSUS(221)` log.

**Review by kantai — APPROVED** [review]

**Review by kantai — COMMENTED** [review]
This looks good to me! Will approve once the CI is sorted.

**Review by jcnelson — APPROVED** [review]
This passes locally for me.  Approving pending passing CI.

**Comment by obycode** [comment]
Ok, flakiness removed in several tests and ready for re-reviews.

**Review by jcnelson — APPROVED** [review]

**Review by jferrant — APPROVED** [review]

**Review by kantai — APPROVED** [review]

**Pull request merged**
