### PR TITLE
Solo Stacking stateful property-based tests

### PR DESCRIPTION
**Pull request by BowTiedRadone**
### Description
This PR is a continuation of https://github.com/stacks-network/stacks-core/pull/4550. It adds the solo stacking scenarios to the *stateful* property-based testing strategy for PoX-4.

### Applicable issues

- https://github.com/stacks-network/stacks-core/issues/4548

### CODE REVIEW

**Review by moodmosaic — DISMISSED** [review]
LGTM 👍 This follows the same strategy we used for the pool delegate stacking scenarios.

**Comment by hugocaillard** [comment]
@moodmosaic @BowTiedRadone What do you think about including these changes in this PR
https://github.com/stacks-network/stacks-core/pull/4550#issuecomment-2072440308

**Comment by moodmosaic** [comment]
> @moodmosaic @BowTiedRadone What do you think about including these changes in this PR [#4550 (comment)](https://github.com/stacks-network/stacks-core/pull/4550#issuecomment-2072440308)

That's the plan. It will be in a folder `boot-contracts-stateful-prop-tests`:

* `boot-contracts-unit-tests` (https://github.com/stacks-network/stacks-core/pull/4698)
* `boot-contracts-prop-tests` (reserved for property-test version of https://github.com/stacks-network/stacks-core/pull/4698)
* `boot-contracts-stateful-prop-tests` (this PR)

**Review by hugocaillard — APPROVED** [review]
LGTM! 🔥

**Review by friedger — APPROVED** [review]
Relocation of files makes sense.

**Review by moodmosaic — APPROVED** [review]
LGTM 🪐

**Pull request merged**
