### PR TITLE
feat: make `chain_id` configurable

### PR DESCRIPTION
**Pull request by obycode**
### Applicable issues

- fixes #

### Checklist

- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Review by jferrant — APPROVED** [review]

**Review by kantai — APPROVED** [review]

**Review by jferrant — DISMISSED** [review]

**Review by kantai — APPROVED** [review]

**Review by jferrant — APPROVED** [review]

**Review by kantai — APPROVED** [review]

**Review by jcnelson — APPROVED** [review]
Approving, but please test this (or add tests) before merging to confirm that once the `PeerDB` is connected, the `LocalPeer` you load out of it has a `network_id` equal to `chain_id`.

**Comment by kantai** [comment]
> Are there any existing tests that might be a good setup for this that you could point me to?

You could add an assertion to any of the neon or nakamoto integration tests by querying /v2/info

**Comment by obycode** [comment]
> You could add an assertion to any of the neon or nakamoto integration tests by querying /v2/info

Cool, I was thinking about adding an integration test with this any way.

**Review by jcnelson — DISMISSED** [review]

**Review by jcnelson — APPROVED** [review]
Approved pending CI

**Review by jferrant — APPROVED** [review]

**Pull request merged**
