### PR TITLE
Merge develop into next

### PR DESCRIPTION
**Pull request by wileyj**
Merging develop into next

### CODE REVIEW

**Comment by wileyj** [comment]
some small additions added to what's coming down from develop:
- updated `testnet/stacks-node/src/mockamoto/tests.rs` to use `insert` rather than `push` (this caused a build failure)
- moved the tests that were in next's `bitcoin-tests.yml` file to a new file `sbtc-tests.yml`
- added a small ci change to `standalone-tests.yml` to enable running the sbtc tests manually

@jferrant -
should these tests run on every PR, or perhaps only on release etc?
https://github.com/stacks-network/stacks-core/actions/runs/7109185874/job/19353942110
3 of tests timed out with a timer of 30 minutes. should this be increased (or reduce the number of retries?)

**Review by obycode — APPROVED** [review]
LGTM 🙌

**Comment by jcnelson** [comment]
@wileyj all the sBTC tests can be deleted, because they correspond to an outdated implementation that's going to be dropped in Neon anyway.

**Comment by xoloki** [comment]
@wileyj `test_stackerdb_dkg` is broken in `next` but easily fixable:

```
INFO [1701883452.632897] [stackslib/src/net/httpcore.rs:985] [p2p-(127.0.0.1:46780,127.0.0.1:47622)] Handle StacksHttpRequest, verb: POST, peer_addr: 127.0.0.1:40312, path: /v2/transactions, query: 
Submit tx error: {"error":"transaction rejected","reason":"FeeTooLow","reason_data":{"actual":10000,"expected":14799},"txid":"ea98fff68bc85723dd3a6256b50d3217427ae1d36eb3a7c46042998fe63c21b0"}
thread 'tests::signer::test_stackerdb_dkg' panicked at '', testnet/stacks-node/src/tests/neon_integrations.rs:652:9
```

**Comment by wileyj** [comment]
> @wileyj `test_stackerdb_dkg` is broken in `next` but easily fixable:
> 
> ```
> INFO [1701883452.632897] [stackslib/src/net/httpcore.rs:985] [p2p-(127.0.0.1:46780,127.0.0.1:47622)] Handle StacksHttpRequest, verb: POST, peer_addr: 127.0.0.1:40312, path: /v2/transactions, query: 
> Submit tx error: {"error":"transaction rejected","reason":"FeeTooLow","reason_data":{"actual":10000,"expected":14799},"txid":"ea98fff68bc85723dd3a6256b50d3217427ae1d36eb3a7c46042998fe63c21b0"}
> thread 'tests::signer::test_stackerdb_dkg' panicked at '', testnet/stacks-node/src/tests/neon_integrations.rs:652:9
> ```

ok. are the changes i've made here (moving the *new* tests to a separate workflow) good enough to merge this, or would some additional work be preferred?

right now, the new tests are only triggered manually (but they can be set to trigger on pr, etc).

**Comment by xoloki** [comment]
Same error in `develop`:
```
INFO [1701883707.548140] [stackslib/src/net/httpcore.rs:986] [p2p-(127.0.0.1:13909,127.0.0.1:59045)] Handle StacksHttpRequest, verb: POST, peer_addr: 127.0.0.1:54166, path: /v2/transactions, query: 
Submit tx error: {"error":"transaction rejected","reason":"FeeTooLow","reason_data":{"actual":10000,"expected":14786},"txid":"aa01876832ccb9918153cf7f9a4d01a3c732c8b2fb0c34f215ea54996a85e148"}
thread 'tests::signer::test_stackerdb_dkg' panicked at '', testnet/stacks-node/src/tests/neon_integrations.rs:600:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by xoloki** [comment]
Same error in this PR branch:
```
Submit tx error: {"error":"transaction rejected","reason":"FeeTooLow","reason_data":{"actual":10000,"expected":14789},"txid":"a90e8bc51fe037be6a755304b0772d3a4c2ff1fc4e7b12db7d587b01b2baaed5"}
thread 'tests::signer::test_stackerdb_dkg' panicked at '', testnet/stacks-node/src/tests/neon_integrations.rs:652:9
```

**Comment by xoloki** [comment]
> ok. are the changes i've made here (moving the _new_ tests to a separate workflow) good enough to merge this, or would some additional work be preferred?
> 
> right now, the new tests are only triggered manually (but they can be set to trigger on pr, etc).

I think you can just merge this PR as is (modulo any other concerns).  We can fix this test in a follow on, and worry about when it runs then.  Personally I'd argue it should run in CI for every PR, though with a smaller signer set so it runs faster.

**Review by jferrant — APPROVED** [review]

**Pull request merged**
