### PR TITLE
feat(mining): use bitcoin wallet name from config

### PR DESCRIPTION
**Pull request by bestmike007**
### Description

Some bitcoin rpc methods require a wallet name, so we use the wallet name config from `Stacks.toml`.

### Checklist

- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Comment by AshtonStephens** [comment]
Which Bitcoin version are you using?

**Comment by bestmike007** [comment]
26.0, I created a non-descriptors wallet add address in watch mode.

**Comment by jcnelson** [comment]
This is going to be tough to merge because `master` uses Bitcoin 22 (I think, cc @wileyj), which complicates testing via CI.  I don't think this problem exists in `develop` if you just want to run that branch.

**Comment by wileyj** [comment]
> This is going to be tough to merge because `master` uses Bitcoin 22 (I think, cc @wileyj), which complicates testing via CI. I don't think this problem exists in `develop` if you just want to run that branch.

Currently `master` is using btc 0.20 (22.x  is the last release where bitcoind will create a default wallet).
agreed that this should be rebased on `develop` @bestmike007

**Comment by bestmike007** [comment]
@wileyj let me rebase develop. I thought it can be configured as empty for old version of bitcoind.

**Comment by bestmike007** [comment]
It's using the wallet name from the config on develop branch. Let me close this.

**Pull request closed without merging**
