### PR TITLE
fix: update `/v2/stacker_set/` to `/v3/stacker_set/`

### PR DESCRIPTION
**Pull request by obycode**
Matches latest node release, 2.5.0.0.7.

### CODE REVIEW

**Review by jcnelson — CHANGES_REQUESTED** [review]
You also need `/v3/block_proposal`

**Review by jcnelson — DISMISSED** [review]

**Review by wileyj — DISMISSED** [review]

**Review by jferrant — APPROVED** [review]

**Review by jcnelson — CHANGES_REQUESTED** [review]
NACK'ing for the moment.  Seems a bunch of tests broke from this.  Let's get them fixed first.

**Comment by wileyj** [comment]
i may have a commit to address this with @jferrant help. running tests locally to confirm

**Comment by wileyj** [comment]
Most tests are passing, but there is still one that's faiiling (not a 404 panic at least):
`tests::signer::v0::end_of_tenure`

fails with:
```
INFO [1725917597.100188] [testnet/stacks-node/src/tests/signer/mod.rs:488] [tests::signer::v0::end_of_tenure] Get current reward cycle: block_height = 239, rc = 11
thread 'tests::signer::v0::end_of_tenure' panicked at testnet/stacks-node/src/tests/signer/v0.rs:1770:5:
assertion `left == right` failed
  left: 11
 right: 12
```

**Review by jcnelson — APPROVED** [review]

**Comment by obycode** [comment]
Looks like `end_of_tenure` passed. `multiple_miners` is fixed in #5075 and @jbencin was looking into `mock_mining`.

**Pull request merged**
