### PR TITLE
feat: Fuzzing for FeeRate Estimates

### LINKED ISSUE #2954: Improved fee estimation
The current fee estimator looks at _mined blocks_, and ranks the transactions in the block by their fee rate, taking the 5th, 50th, and 95th percentiles, and uses those three values as fee rate estimates.

This can lead to some problems -- it seems like very high fee estimates can be commonly obtained when STX transfers are broadcasted with fee amounts around 1 STX (STX transfers are much cheaper operations than contract-calls, like 50-100x cheaper, so when most transfers use fees around 1 STX, they imply that contract-calls should be 50-100 STX).

### PR DESCRIPTION
**Pull request by gregorycoppola**
Addresses #2954

We are implementing the four points in https://github.com/blockstack/stacks-blockchain/issues/2954#issuecomment-983017453

#2966 addresses the first three points.

Here, we address:
4. We should address fee changes in the face of congestion using a strategy of **"fuzzing"** the estimated fee rate: when queried, nodes will add some random noise to the estimated fee rate. In periods of congestion, clients that used the higher fee would be included in the next block, pushing the fee estimate for the next block up.

This is tested just by the new unit tests.

### CODE REVIEW

**Comment by jcnelson** [comment]
How to test:

* During high congestion, we want users with higher fees to be accepted with higher probability.
* The integration test we need is to submit enough transactions to congest the network, and we're able to measure the average? median? fee rate going up.

**Comment by gregorycoppola** [comment]
> How to test:
> 
>     * During high congestion, we want users with higher fees to be accepted with higher probability.
For the integration test, I plan to mostly just test that the program:
1) starts
2) allows us to call the right estimator

I didn't plan to validate the entire strategy round-trip.

We can add that.


> 
>     * The integration test we need is to submit enough transactions to congest the network, and we're able to measure the average? median? fee rate going up.

**Comment by gregorycoppola** [comment]
Well, we *could* add an experiment for the round-trip working.

But, we don't need an integration test for that, I think. We just need to verify:
1) From the unit tests, any calculations we want
2) From the integration test, that we can boot up with the estimator we wanted

**Comment by kantai** [comment]
> Well, we could add an experiment for the round-trip working.
> But, we don't need an integration test for that, I think. We just need to verify:
>
>    From the unit tests, any calculations we want
>    From the integration test, that we can boot up with the estimator we wanted

I think we do need an integration test. The behavior we're trying to measure is that (1) the fuzzer introduces a distribution into client's fee rates, (2) based on this distribution, the default miner will prefer the higher fee rate transactions, and (3) the assembled blocks will cause fee rates estimates to increase.

Testing that requires testing that all the pieces of this (miner, fee estimator, fee estimation RPC, and mempool iterator) work together to get the behavior we want: that's an integration test. It may be possible to use the `TestPeer` based testing structure to achieve this as well, but that's similarly a kind of integration test.

**Comment by gregorycoppola** [comment]
see https://github.com/blockstack/stacks-blockchain/pull/2972

**Pull request closed without merging**
