### PR TITLE
Update wsts version to 6.0 and use Packet::verify function

### PR DESCRIPTION
**Pull request by jferrant**
### Description
Need the newest wsts version changes for handling <100% participation in DKG
Also required for processing coordinator messages while in the IDLE state which enables DKG to be calculated by all signers simultaneously

### Applicable issues

- Part of https://github.com/stacks-network/stacks-core/issues/4111
- Part of https://github.com/stacks-network/stacks-core/issues/3972

### CODE REVIEW

**Review by xoloki — APPROVED** [review]
Lgtm as long as CI (test_stackerdb_dkg specifically) passes

**Comment by jcnelson** [comment]
I don't think the stackerdb tests are running here?

**Review by kantai — APPROVED** [review]

**Comment by xoloki** [comment]
@jferrant I changed the issue description to specify that this does not close #4111, but it is a part of it.  I don't think we should close #4111 until I do that last piece of robustness, i.e. allow partial DkgPrivateShares participation as long as a DKG threshold subset of the DkgPublicShares responders also send private shares.

**Comment by xoloki** [comment]
> I don't think the stackerdb tests are running here?

I ran `test_stackerdb_dkg` locally, and it passed.  But yeah I don't see an explicit CI action  that calls it @jcnelson

**Comment by xoloki** [comment]
Ok @jcnelson it looks like `test_stackerdb_dkg` and the other `StackerDB` tests are part of `sbtc-tests.yml`, not `bitcoin-tests.yml`, and they aren't running currently.  @wileyj is there some reason the `sBTC`/`StackerDB` tests aren't running currently?  I know they take a while, but are they flakey in CI?

**Pull request merged**
