### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by wileyj**
@jcnelson @kantai @obycode @jferrant @xoloki 

could use some help here to iron out any additional paths that should be added . 
Once enforced, the idea is to require a codeowner (listed in the file in this PR) to approve a PR before it can merge. 
by default, jcnelson/kantai/obycode will be added to all PR's unless specified later in the file (ex: wileyj/charliec3 will be added to PR's changing CI workflows). 

what i've added so far is a best guess based on commit history, but i think it can/should be ironed out a bit more before enforcing. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

```
# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
# @global-owner1 and @global-owner2 will be requested for
# review when someone opens a pull request.
* @jcnelson @kantai @obycode

# Generic file extensions that shouldn't require much scrutiny
*.md @stacks-network/blockchain-team
*.yml @stacks-network/blockchain-team
*.yaml @stacks-network/blockchain-team
*.txt @stacks-network/blockchain-team
*.toml @stacks-network/blockchain-team

# Signer code
libsigner/**/*.rs @jferrant @xoloki @jcnelson @kantai
stacks-signer/**/*.rs @jferrant @xoloki @jcnelson @kantai

## CI workflows
./github/workflows/ @wileyj @CharlieC3
./github/actions/ @wileyj @CharlieC3
```

### CODE REVIEW

**Comment by wileyj** [comment]
for now, keeping user id's is fine - but i'm also thinking that some new teams in the org would be be easier to manage longer-term. 
once we have a good list of who should be approving PR's for specific parts of the codebase, i'll adjust to add teams so any changes won't require another PR.

**Comment by jferrant** [comment]
I have no problem with it :)

**Review by jcnelson — DISMISSED** [review]
Works for me! Happy to delegate if needed

**Comment by wileyj** [comment]
thanks! once i setup appropriate teams i'll adjust the file. 
in the meantime, if there specific changes anyone would like to see let me know and i'll add

**Review by obycode — DISMISSED** [review]
👍

**Review by xoloki — APPROVED** [review]
LGTM

**Review by jferrant — APPROVED** [review]

**Comment by wileyj** [comment]
now that 2.5 is out, should this be rebased against develop?

**Comment by wileyj** [comment]
rebased against `develop` - diverging from the PR text a little, i've moved to a team based approach vs hard-coding usernames in the file. this will make it easier to maintain. 

there are some paths in the repo that i wasn't sure should have a team directly added as a codeowner, but i'm open to adjusting based on any suggestions.

**Review by obycode — APPROVED** [review]

**Review by jcnelson — APPROVED** [review]

**Pull request merged**
